general:
  log_level: info

mqtt:
  host: 10.0.0.2
  port: 1883
  user: deez
  password: hunter2

tasmota:
  devgroups:
    dining_room:
    # list of zigbee2mqtt friendly names (can include Zigbee groups)
    - 'Dining room light'
    - 'Dining room buffet light'
    bedroom:
    - 'Bedroom light'
    - 'Ledroom bight'
  devgroup_address: '239.255.250.250' # default
  devgroup_port: 4447 # default

zigbee2mqtt:
  base_topic: 'zigbee2mqtt'
